### ISSUE TITLE
Mass erase in case of disabled bootloader and partly disabled JTAG access

### ISSUE THREAD

**Issue by nanosonde** [homemcu/jlinkscript.cc31x0-cc26x0.chiperase#1]
Can I use your script to "unbrick" a CC1310 with disabled bootloader and JTAG access?

From what I have understood from [here](https://e2e.ti.com/support/wireless-connectivity/sub-1-ghz/f/156/t/609938?CC1310-Regarding-Source-Code-IP-Protection-Features-in-CC1310-CC1350-Devices-), there is a chance to lock out yourself by accidently overwriting the CCFG area in the chip.

**Comment by homemcu** [comment]
Sorry for the late response.
This script is for those who have custom CC1310 boards, but not have XDS100v3, so they can not use TI Flash Programmer 2 with the mass erase function. The script is for J-LINKv8 (may be for v9 too, I didn't try) and it uses CHIP_ERASE_REQ and SYS_RESET_REQ features supported through JTAG WUC TAP. So if you do not disable chip erase in the  ERASE_CONF Register the script should be work.
